// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./src/components/Backtop/src/Backtop.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/src/Breadcrumb.vue')['default']
    Collapse: typeof import('./src/components/Collapse/src/Collapse.vue')['default']
    ColorRadioPicker: typeof import('./src/components/Setting/src/components/ColorRadioPicker.vue')['default']
    ConfigGlobal: typeof import('./src/components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/src/ContextMenu.vue')['default']
    CountTo: typeof import('./src/components/CountTo/src/CountTo.vue')['default']
    Descriptions: typeof import('./src/components/Descriptions/src/Descriptions.vue')['default']
    Dialog: typeof import('./src/components/Dialog/src/Dialog.vue')['default']
    Editor: typeof import('./src/components/Editor/src/Editor.vue')['default']
    Error: typeof import('./src/components/Error/src/Error.vue')['default']
    Footer: typeof import('./src/components/Footer/src/Footer.vue')['default']
    Form: typeof import('./src/components/Form/src/Form.vue')['default']
    Highlight: typeof import('./src/components/Highlight/src/Highlight.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer/src/ImageViewer.vue')['default']
    Infotip: typeof import('./src/components/Infotip/src/Infotip.vue')['default']
    InputPassword: typeof import('./src/components/InputPassword/src/InputPassword.vue')['default']
    InterfaceDisplay: typeof import('./src/components/Setting/src/components/InterfaceDisplay.vue')['default']
    LayoutRadioPicker: typeof import('./src/components/Setting/src/components/LayoutRadioPicker.vue')['default']
    LocaleDropdown: typeof import('./src/components/LocaleDropdown/src/LocaleDropdown.vue')['default']
    Logo: typeof import('./src/components/Logo/src/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/src/Screenfull.vue')['default']
    Search: typeof import('./src/components/Search/src/Search.vue')['default']
    Setting: typeof import('./src/components/Setting/src/Setting.vue')['default']
    SizeDropdown: typeof import('./src/components/SizeDropdown/src/SizeDropdown.vue')['default']
    Sticky: typeof import('./src/components/Sticky/src/Sticky.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TagsView: typeof import('./src/components/TagsView/src/TagsView.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/src/UserInfo.vue')['default']
  }
}
